name: Blog Oscar Orsini
favicon: null
layout_spectrum: 0.75122
typography_spectrum: 0.43993
title: Artículos de liderazgo sobre la vida cotidiana y el trabajo
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0b87dd'
    - '#3b6188'
    - '#96cdf7'
    - '#6c86a6'
  brandStrength: 1
  lightness: 0.625
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
