name: Blog Oscar Orsini
favicon: null
layout_spectrum: 0.74159
typography_spectrum: 0.43993
title: Artículos de la vida cotidiana sobre Liderazgo
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6479036279488355
  lightness: 0.33547702245414257
  saturation: 0.12305956915952265
  rhythmicContrast: 0.529096654150635
purpose: []
