name: Blog Oscar Orsini
favicon: null
layout_spectrum: 0.91498
typography_spectrum: 0.43993
title: Artículos de liderazgo sobre la vida cotidiana y el trabajo
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0b87dd'
    - '#3b6188'
    - '#96cdf7'
    - '#6c86a6'
  brandStrength: 0.6479036279488355
  lightness: 0.33547702245414257
  saturation: 0.12305956915952265
  rhythmicContrast: 0.529096654150635
purpose: []
